set nocompatible

" Colors

syntax enable

" Spaces & Tabs
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
set expandtab

" UI Config

set number
set cursorline
set lazyredraw
set showmatch
filetype indent on
set autoindent
set cindent

" allows cursor change in tmux mode
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" Searching

set incsearch
set hlsearch
set ignorecase

